
package com.irctc.endpoint.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ERailImplService", targetNamespace = "http://impl.endpoint.irctc.com/", wsdlLocation = "http://localhost:8085/TicketBookingService/getTicket?wsdl")
public class ERailImplService
    extends Service
{

    private final static URL ERAILIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERAILIMPLSERVICE_EXCEPTION;
    private final static QName ERAILIMPLSERVICE_QNAME = new QName("http://impl.endpoint.irctc.com/", "ERailImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/TicketBookingService/getTicket?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERAILIMPLSERVICE_WSDL_LOCATION = url;
        ERAILIMPLSERVICE_EXCEPTION = e;
    }

    public ERailImplService() {
        super(__getWsdlLocation(), ERAILIMPLSERVICE_QNAME);
    }

    public ERailImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERAILIMPLSERVICE_QNAME, features);
    }

    public ERailImplService(URL wsdlLocation) {
        super(wsdlLocation, ERAILIMPLSERVICE_QNAME);
    }

    public ERailImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERAILIMPLSERVICE_QNAME, features);
    }

    public ERailImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ERailImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ERailService
     */
    @WebEndpoint(name = "ERailImplPort")
    public ERailService getERailImplPort() {
        return super.getPort(new QName("http://impl.endpoint.irctc.com/", "ERailImplPort"), ERailService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ERailService
     */
    @WebEndpoint(name = "ERailImplPort")
    public ERailService getERailImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.endpoint.irctc.com/", "ERailImplPort"), ERailService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERAILIMPLSERVICE_EXCEPTION!= null) {
            throw ERAILIMPLSERVICE_EXCEPTION;
        }
        return ERAILIMPLSERVICE_WSDL_LOCATION;
    }

}
