
package org.myinsurancepolicy.plan.types;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsuranceServiceImplService", targetNamespace = "http://types.plan.myinsurancepolicy.org/", wsdlLocation = "http://localhost:8085/InsurancePlanCFAProvider/getplan?wsdl")
public class InsuranceServiceImplService
    extends Service
{

    private final static URL INSURANCESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException INSURANCESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName INSURANCESERVICEIMPLSERVICE_QNAME = new QName("http://types.plan.myinsurancepolicy.org/", "InsuranceServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/InsurancePlanCFAProvider/getplan?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSURANCESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        INSURANCESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public InsuranceServiceImplService() {
        super(__getWsdlLocation(), INSURANCESERVICEIMPLSERVICE_QNAME);
    }

    public InsuranceServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSURANCESERVICEIMPLSERVICE_QNAME, features);
    }

    public InsuranceServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, INSURANCESERVICEIMPLSERVICE_QNAME);
    }

    public InsuranceServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSURANCESERVICEIMPLSERVICE_QNAME, features);
    }

    public InsuranceServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsuranceServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EInsuranceTest
     */
    @WebEndpoint(name = "InsuranceServiceImplPort")
    public EInsuranceTest getInsuranceServiceImplPort() {
        return super.getPort(new QName("http://types.plan.myinsurancepolicy.org/", "InsuranceServiceImplPort"), EInsuranceTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EInsuranceTest
     */
    @WebEndpoint(name = "InsuranceServiceImplPort")
    public EInsuranceTest getInsuranceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://types.plan.myinsurancepolicy.org/", "InsuranceServiceImplPort"), EInsuranceTest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSURANCESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw INSURANCESERVICEIMPLSERVICE_EXCEPTION;
        }
        return INSURANCESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
