//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.30 at 11:42:04 PM IST 
//


package in.ms.project.types;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="proj-id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="proj-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="proj-date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectType", propOrder = {
    "projId",
    "projName",
    "projDate"
})
@XmlRootElement(name="project")
public class ProjectType {

    @Override
	public String toString() {
		return "ProjectType [projId=" + projId + ", projName=" + projName + ", projDate=" + projDate + "]";
	}

	@XmlElement(name = "proj-id")
    protected int projId;
    @XmlElement(name = "proj-name", required = true)
    protected String projName;
    @XmlElement(name = "proj-date", required = true)
    @XmlSchemaType(name = "date")
    protected Date projDate;

    /**
     * Gets the value of the projId property.
     * 
     */
    public int getProjId() {
        return projId;
    }

    /**
     * Sets the value of the projId property.
     * 
     */
    public void setProjId(int value) {
        this.projId = value;
    }

    /**
     * Gets the value of the projName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjName() {
        return projName;
    }

    /**
     * Sets the value of the projName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjName(String value) {
        this.projName = value;
    }

    /**
     * Gets the value of the projDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getProjDate() {
        return projDate;
    }

    /**
     * Sets the value of the projDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setProjDate(Date value) {
        this.projDate = value;
    }

}
