
package org.myinsurancepolicy.plan.types;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EInsuranceTest", targetNamespace = "http://myinsurancepolicy.org/plan/types")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EInsuranceTest {


    /**
     * 
     * @param planType
     * @return
     *     returns org.myinsurancepolicy.plan.types.PlanInfoType
     */
    @WebMethod
    @WebResult(name = "plan-info", targetNamespace = "http://myinsurancepolicy.org/plan/types", partName = "planInfo")
    public PlanInfoType getInsurancePlanInfo(
        @WebParam(name = "plan-type", targetNamespace = "http://myinsurancepolicy.org/plan/types", partName = "planType")
        PlanType planType);

}
