//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.13 at 02:45:48 PM IST 
//


package com.travel.binding;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="domestic-flight" type="{}DomesticFlightType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="international-flight" type="{}InternationalFlightType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "domesticFlight",
    "internationalFlight"
})
@XmlRootElement(name = "travel-agency")
public class TravelAgency {

    @XmlElement(name = "domestic-flight")
    protected List<DomesticFlightType> domesticFlight;
    @XmlElement(name = "international-flight")
    protected List<InternationalFlightType> internationalFlight;

    /**
     * Gets the value of the domesticFlight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the domesticFlight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDomesticFlight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomesticFlightType }
     * 
     * 
     */
    public List<DomesticFlightType> getDomesticFlight() {
        if (domesticFlight == null) {
            domesticFlight = new ArrayList<DomesticFlightType>();
        }
        return this.domesticFlight;
    }

    /**
     * Gets the value of the internationalFlight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internationalFlight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternationalFlight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InternationalFlightType }
     * 
     * 
     */
    public List<InternationalFlightType> getInternationalFlight() {
        if (internationalFlight == null) {
            internationalFlight = new ArrayList<InternationalFlightType>();
        }
        return this.internationalFlight;
    }

	@Override
	public String toString() {
		return "TravelAgency [domesticFlight=" + domesticFlight + ", internationalFlight=" + internationalFlight + "]";
	}

    
}
