
package com.bse.stockendpoint.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bse.stockendpoint.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IStockExchange", targetNamespace = "http://stockendpoint.bse.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IStockExchange {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findStockPrice", targetNamespace = "http://stockendpoint.bse.com/", className = "com.bse.stockendpoint.FindStockPrice")
    @ResponseWrapper(localName = "findStockPriceResponse", targetNamespace = "http://stockendpoint.bse.com/", className = "com.bse.stockendpoint.FindStockPriceResponse")
    public Double findStockPrice(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
