
package com.bse.stockendpoint.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StockExchangeImplService", targetNamespace = "http://impl.stockendpoint.bse.com/", wsdlLocation = "http://localhost:8085/ApacheCXFStockProvider/services/getstock?wsdl")
public class StockExchangeImplService
    extends Service
{

    private final static URL STOCKEXCHANGEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STOCKEXCHANGEIMPLSERVICE_EXCEPTION;
    private final static QName STOCKEXCHANGEIMPLSERVICE_QNAME = new QName("http://impl.stockendpoint.bse.com/", "StockExchangeImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/ApacheCXFStockProvider/services/getstock?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKEXCHANGEIMPLSERVICE_WSDL_LOCATION = url;
        STOCKEXCHANGEIMPLSERVICE_EXCEPTION = e;
    }

    public StockExchangeImplService() {
        super(__getWsdlLocation(), STOCKEXCHANGEIMPLSERVICE_QNAME);
    }

    public StockExchangeImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKEXCHANGEIMPLSERVICE_QNAME, features);
    }

    public StockExchangeImplService(URL wsdlLocation) {
        super(wsdlLocation, STOCKEXCHANGEIMPLSERVICE_QNAME);
    }

    public StockExchangeImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKEXCHANGEIMPLSERVICE_QNAME, features);
    }

    public StockExchangeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockExchangeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IStockExchange
     */
    @WebEndpoint(name = "StockExchangeImplPort")
    public IStockExchange getStockExchangeImplPort() {
        return super.getPort(new QName("http://impl.stockendpoint.bse.com/", "StockExchangeImplPort"), IStockExchange.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStockExchange
     */
    @WebEndpoint(name = "StockExchangeImplPort")
    public IStockExchange getStockExchangeImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.stockendpoint.bse.com/", "StockExchangeImplPort"), IStockExchange.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKEXCHANGEIMPLSERVICE_EXCEPTION!= null) {
            throw STOCKEXCHANGEIMPLSERVICE_EXCEPTION;
        }
        return STOCKEXCHANGEIMPLSERVICE_WSDL_LOCATION;
    }

}
