
package com.irctc.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ERailService", targetNamespace = "http://endpoint.irctc.com/", wsdlLocation = "file:/D:/XMLWebServices/JAX-B/Book/GetBook.wsdl")
public class ERailService_Service
    extends Service
{

    private final static URL ERAILSERVICE_WSDL_LOCATION;
    private final static WebServiceException ERAILSERVICE_EXCEPTION;
    private final static QName ERAILSERVICE_QNAME = new QName("http://endpoint.irctc.com/", "ERailService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/XMLWebServices/JAX-B/Book/GetBook.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERAILSERVICE_WSDL_LOCATION = url;
        ERAILSERVICE_EXCEPTION = e;
    }

    public ERailService_Service() {
        super(__getWsdlLocation(), ERAILSERVICE_QNAME);
    }

    public ERailService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERAILSERVICE_QNAME, features);
    }

    public ERailService_Service(URL wsdlLocation) {
        super(wsdlLocation, ERAILSERVICE_QNAME);
    }

    public ERailService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERAILSERVICE_QNAME, features);
    }

    public ERailService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ERailService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ERailService
     */
    @WebEndpoint(name = "ERailImplPort")
    public ERailService getERailImplPort() {
        return super.getPort(new QName("http://endpoint.irctc.com/", "ERailImplPort"), ERailService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ERailService
     */
    @WebEndpoint(name = "ERailImplPort")
    public ERailService getERailImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.irctc.com/", "ERailImplPort"), ERailService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ERAILSERVICE_EXCEPTION!= null) {
            throw ERAILSERVICE_EXCEPTION;
        }
        return ERAILSERVICE_WSDL_LOCATION;
    }

}
