
package com.irctc.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "eRailService", targetNamespace = "http://endpoint.irctc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ERailService {


    /**
     * 
     * @param personData
     * @param journeyData
     * @return
     *     returns com.irctc.endpoint.TicketInfo
     */
    @WebMethod
    @WebResult(name = "ReturnTicketinfo", targetNamespace = "")
    @RequestWrapper(localName = "bookTrainTicket", targetNamespace = "http://endpoint.irctc.com/", className = "com.irctc.endpoint.BookTrainTicket")
    @ResponseWrapper(localName = "bookTrainTicketResponse", targetNamespace = "http://endpoint.irctc.com/", className = "com.irctc.endpoint.BookTrainTicketResponse")
    @Action(input = "http://endpoint.irctc.com/eRailService/bookTrainTicketRequest", output = "http://endpoint.irctc.com/eRailService/bookTrainTicketResponse")
    public TicketInfo bookTrainTicket(
        @WebParam(name = "PersonData", targetNamespace = "")
        PassengerInfo personData,
        @WebParam(name = "journeyData", targetNamespace = "")
        JourneyInfo journeyData);

}
