
package com.flipkart.mobile.mi;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import org.payments.paytm.binding.AccountInfoRequest;
import org.payments.paytm.binding.InvoiceInfo;
import org.payments.paytm.binding.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAtm", targetNamespace = "http://flipkart.com/mobile/mi")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAtm {


    /**
     * 
     * @param acoountData
     * @return
     *     returns org.payments.paytm.binding.InvoiceInfo
     */
    @WebMethod
    @WebResult(name = "invoice-info-response", targetNamespace = "http://paytm.payments.org/binding", partName = "parameter")
    @Action(input = "http://flipkart.com/mobile/mi/IAtm/getInvoiceInfoRequest", output = "http://flipkart.com/mobile/mi/IAtm/getInvoiceInfoResponse")
    public InvoiceInfo getInvoiceInfo(
        @WebParam(name = "account-info-request", targetNamespace = "http://paytm.payments.org/binding", partName = "acoount-data")
        AccountInfoRequest acoountData);

}
