
package com.udai.adhar.endpoint.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.udai.adhar.endpoint.ObjectFactory;
import com.udai.adhar.endpoint.Person;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IUidai", targetNamespace = "http://endpoint.adhar.udai.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IUidai {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adharEnroll", targetNamespace = "http://endpoint.adhar.udai.com/", className = "com.udai.adhar.endpoint.AdharEnroll")
    @ResponseWrapper(localName = "adharEnrollResponse", targetNamespace = "http://endpoint.adhar.udai.com/", className = "com.udai.adhar.endpoint.AdharEnrollResponse")
    public Long adharEnroll(
        @WebParam(name = "arg0", targetNamespace = "")
        Person arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.udai.adhar.endpoint.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAdharData", targetNamespace = "http://endpoint.adhar.udai.com/", className = "com.udai.adhar.endpoint.GetAdharData")
    @ResponseWrapper(localName = "getAdharDataResponse", targetNamespace = "http://endpoint.adhar.udai.com/", className = "com.udai.adhar.endpoint.GetAdharDataResponse")
    public Person getAdharData(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
