
package com.udai.adhar.endpoint.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IUidaiImplService", targetNamespace = "http://impl.endpoint.adhar.udai.com/", wsdlLocation = "http://localhost:8085/SpringMVCAdharAppWithB2B/webser/getData?wsdl")
public class IUidaiImplService
    extends Service
{

    private final static URL IUIDAIIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException IUIDAIIMPLSERVICE_EXCEPTION;
    private final static QName IUIDAIIMPLSERVICE_QNAME = new QName("http://impl.endpoint.adhar.udai.com/", "IUidaiImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/SpringMVCAdharAppWithB2B/webser/getData?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IUIDAIIMPLSERVICE_WSDL_LOCATION = url;
        IUIDAIIMPLSERVICE_EXCEPTION = e;
    }

    public IUidaiImplService() {
        super(__getWsdlLocation(), IUIDAIIMPLSERVICE_QNAME);
    }

    public IUidaiImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IUIDAIIMPLSERVICE_QNAME, features);
    }

    public IUidaiImplService(URL wsdlLocation) {
        super(wsdlLocation, IUIDAIIMPLSERVICE_QNAME);
    }

    public IUidaiImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IUIDAIIMPLSERVICE_QNAME, features);
    }

    public IUidaiImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IUidaiImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IUidai
     */
    @WebEndpoint(name = "IUidaiImplPort")
    public IUidai getIUidaiImplPort() {
        return super.getPort(new QName("http://impl.endpoint.adhar.udai.com/", "IUidaiImplPort"), IUidai.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IUidai
     */
    @WebEndpoint(name = "IUidaiImplPort")
    public IUidai getIUidaiImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.endpoint.adhar.udai.com/", "IUidaiImplPort"), IUidai.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IUIDAIIMPLSERVICE_EXCEPTION!= null) {
            throw IUIDAIIMPLSERVICE_EXCEPTION;
        }
        return IUIDAIIMPLSERVICE_WSDL_LOCATION;
    }

}
