
package com.nit.calc.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.nit.calc.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calc", targetNamespace = "http://calc.nit.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calc {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiple", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.Multiple")
    @ResponseWrapper(localName = "multipleResponse", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.MultipleResponse")
    @Action(input = "http://calc.nit.com/Calc/multipleRequest", output = "http://calc.nit.com/Calc/multipleResponse")
    public Integer multiple(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "additon", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.Additon")
    @ResponseWrapper(localName = "additonResponse", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.AdditonResponse")
    @Action(input = "http://calc.nit.com/Calc/additonRequest", output = "http://calc.nit.com/Calc/additonResponse")
    public Integer additon(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.DivisionResponse")
    @Action(input = "http://calc.nit.com/Calc/divisionRequest", output = "http://calc.nit.com/Calc/divisionResponse")
    public Integer division(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "remaider", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.Remaider")
    @ResponseWrapper(localName = "remaiderResponse", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.RemaiderResponse")
    @Action(input = "http://calc.nit.com/Calc/remaiderRequest", output = "http://calc.nit.com/Calc/remaiderResponse")
    public Integer remaider(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "substract", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.Substract")
    @ResponseWrapper(localName = "substractResponse", targetNamespace = "http://calc.nit.com/", className = "com.nit.calc.SubstractResponse")
    @Action(input = "http://calc.nit.com/Calc/substractRequest", output = "http://calc.nit.com/Calc/substractResponse")
    public Integer substract(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Integer arg1);

}
