
package in.tekleads.book.types;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EBookService", targetNamespace = "http://tekleads.in/book/types")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EBookService {


    /**
     * 
     * @param parameter
     * @return
     *     returns in.tekleads.book.types.BookResponseType
     */
    @WebMethod
    @WebResult(name = "bookResponseType", targetNamespace = "http://tekleads.in/book/types", partName = "parameter")
    public BookResponseType getBookByIsbn(
        @WebParam(name = "bookRequestType", targetNamespace = "http://tekleads.in/book/types", partName = "parameter")
        BookRequestType parameter);

}
