
package in.tekleads.book.types;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EBookService", targetNamespace = "http://tekleads.in/book/types", wsdlLocation = "file:/D:/XMLWebServices/JAX-B/Dummy/Book.wsdl")
public class EBookService_Service
    extends Service
{

    private final static URL EBOOKSERVICE_WSDL_LOCATION;
    private final static WebServiceException EBOOKSERVICE_EXCEPTION;
    private final static QName EBOOKSERVICE_QNAME = new QName("http://tekleads.in/book/types", "EBookService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/XMLWebServices/JAX-B/Dummy/Book.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EBOOKSERVICE_WSDL_LOCATION = url;
        EBOOKSERVICE_EXCEPTION = e;
    }

    public EBookService_Service() {
        super(__getWsdlLocation(), EBOOKSERVICE_QNAME);
    }

    public EBookService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EBOOKSERVICE_QNAME, features);
    }

    public EBookService_Service(URL wsdlLocation) {
        super(wsdlLocation, EBOOKSERVICE_QNAME);
    }

    public EBookService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EBOOKSERVICE_QNAME, features);
    }

    public EBookService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EBookService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EBookService
     */
    @WebEndpoint(name = "EBookserviceImplPort")
    public EBookService getEBookserviceImplPort() {
        return super.getPort(new QName("http://tekleads.in/book/types", "EBookserviceImplPort"), EBookService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EBookService
     */
    @WebEndpoint(name = "EBookserviceImplPort")
    public EBookService getEBookserviceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tekleads.in/book/types", "EBookserviceImplPort"), EBookService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EBOOKSERVICE_EXCEPTION!= null) {
            throw EBOOKSERVICE_EXCEPTION;
        }
        return EBOOKSERVICE_WSDL_LOCATION;
    }

}
